import type { Language } from '../core/i18n/translations.types';
import type { PolicyDocCopy, PolicySlug } from './policies.page.copy';

const EN: Record<PolicySlug, PolicyDocCopy> = {
  'terms-of-use': {
    slug: 'terms-of-use',
    title: 'Terms of Use',
    summary: 'Rules for using ExploreAI, accounts, content, and disclaimers.',
    subtitle: 'Agreement governing use of the ExploreAI service',
    updated: 'Last updated: 2026-08-09',
    sections: [
      {
        heading: 'Agreement',
        paragraphs: [
          'These Terms of Use (“Terms”) govern access to and use of ExploreAI (the “Service”), including chat, retrieval, generation, and related tools offered in the product.',
          'By accessing or using the Service, you agree to these Terms. If you do not agree, do not use the Service. This document is a draft for product commercialization and is not a substitute for legal advice.',
        ],
      },
      {
        heading: 'Eligibility',
        paragraphs: [
          'You must be able to form a binding agreement under applicable law. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.',
        ],
      },
      {
        heading: 'Accounts and identity',
        paragraphs: [
          'The Service may be used as a guest with a browser-scoped Client Identity, and may also support optional signed-in accounts when enabled.',
          'You are responsible for activity under your identity or account and for keeping access credentials and devices under your control secure.',
        ],
      },
      {
        heading: 'Acceptable use',
        paragraphs: [
          'You may use the Service only in compliance with these Terms and applicable law. You must not abuse the Service, attempt to bypass rate or plan limits, submit unlawful or harmful content, interfere with other users, or attempt to access data that is not yours.',
          'We may suspend or limit access that harms the Service, other users, or third parties, or that violates these Terms.',
        ],
      },
      {
        heading: 'Your content and model providers',
        paragraphs: [
          'You retain rights in content you submit. You grant ExploreAI a limited license to process that content as needed to operate, secure, and improve the Service, including transmitting prompts and context to configured model and tool providers.',
          'Do not submit content you are not allowed to share, or sensitive personal data you do not want processed by third-party model providers.',
        ],
      },
      {
        heading: 'Outputs, similarity, and no professional advice',
        paragraphs: [
          'Outputs are generated by machine-learning models and may be inaccurate, incomplete, or similar to content produced for other users. You are responsible for reviewing outputs before relying on them.',
          'The Service does not provide legal, medical, financial, or other professional advice. Do not use outputs as the sole basis for safety-critical or regulated decisions.',
        ],
      },
      {
        heading: 'Third-party services',
        paragraphs: [
          'The Service depends on third-party hosting, model, search, and observability providers. Their terms and privacy practices apply to processing they perform. See the Sub-processors page for the current list.',
        ],
      },
      {
        heading: 'Feedback',
        paragraphs: [
          'If you provide feedback or suggestions, you grant ExploreAI permission to use them without restriction or compensation.',
        ],
      },
      {
        heading: 'Suspension and termination',
        paragraphs: [
          'We may suspend or terminate access for violations of these Terms, risk to the Service, or operational or legal reasons. You may stop using the Service at any time. Provisions that by nature should survive will survive termination.',
        ],
      },
      {
        heading: 'Disclaimers',
        paragraphs: [
          'THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, EXPLOREAI DISCLAIMS WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.',
          'We do not warrant that the Service will be uninterrupted, error-free, or free of harmful components, or that outputs will meet your requirements.',
        ],
      },
      {
        heading: 'Limitation of liability',
        paragraphs: [
          'To the maximum extent permitted by law, ExploreAI and its suppliers will not be liable for indirect, incidental, special, consequential, or punitive damages, or for lost profits, data, or goodwill, arising from use of the Service.',
          'Our aggregate liability for claims relating to the Service is limited to the greater of fees you paid to us for the Service in the three months before the claim or one hundred US dollars (or local equivalent), if no fees were paid.',
        ],
      },
      {
        heading: 'Changes',
        paragraphs: [
          'We may update these Terms as the product evolves. Material changes will be reflected on this page with an updated date. Continued use after changes become effective constitutes acceptance of the revised Terms.',
        ],
      },
      {
        heading: 'Contact',
        paragraphs: [
          'For questions about these Terms, use the Privacy controls page in the product. Operator contact details will be published there as the Service commercializes.',
        ],
      },
    ],
  },
  'privacy-policy': {
    slug: 'privacy-policy',
    title: 'Privacy Policy',
    summary: 'What data we process, why we process it, and your choices.',
    subtitle: 'How ExploreAI processes personal data',
    updated: 'Last updated: 2026-08-09',
    sections: [
      {
        heading: 'Who we are',
        paragraphs: [
          'ExploreAI (“we”, “us”) provides AI chat and related tools. This Privacy Policy explains how we process personal data when you use the Service.',
          'This document is a draft for product commercialization and is not a substitute for legal advice. Interactive preferences and erasure tools are available on the Privacy controls page.',
        ],
      },
      {
        heading: 'Data we process',
        paragraphs: [
          'Depending on how you use the Service, we may process: Client Identity or account identifiers; chat messages, uploads, and related session metadata; optional analytics and feature-flag events if you consent; and technical logs needed for security and reliability.',
          'Do not submit sensitive personal data you do not want processed by model or infrastructure providers.',
        ],
      },
      {
        heading: 'Purposes',
        paragraphs: [
          'We process data to provide and secure the Service, isolate sessions by owner or browser identity, generate model responses, remember preferences you choose, measure reliability when analytics is enabled, and comply with law.',
        ],
      },
      {
        heading: 'Sharing and sub-processors',
        paragraphs: [
          'We share data with sub-processors that help deliver the Service, such as model providers, hosting, and optional observability vendors. We do not sell personal data.',
          'See the Sub-processors page for categories of providers. Those providers process data under their own terms where they act as independent controllers or as our processors, depending on the integration.',
        ],
      },
      {
        heading: 'Retention and erasure',
        paragraphs: [
          'Inactive sessions and aged operational data are purged on a retention schedule (on the order of about ninety days unless a longer period is required for security or legal reasons).',
          'You can erase this browser’s chat sessions and rotate Client Identity from Privacy controls. Signed-in account deletion, when available, will be described on that page.',
        ],
      },
      {
        heading: 'Cookies and similar technologies',
        paragraphs: [
          'We use a necessary Client Identity cookie to scope sessions to your browser. Optional analytics technologies load only if you accept analytics. Details are in the Cookie Policy.',
        ],
      },
      {
        heading: 'Your choices and rights',
        paragraphs: [
          'Depending on your location, you may have rights to access, correct, delete, or restrict processing of personal data, or to object to certain processing. Use Privacy controls for in-product erasure and consent changes.',
          'If a request cannot be completed in-product, contact us through the channel published on Privacy controls as the Service commercializes.',
        ],
      },
      {
        heading: 'International transfers',
        paragraphs: [
          'Model and infrastructure providers may process data in regions where they operate. Where required, we rely on appropriate transfer mechanisms offered by those providers or by applicable law.',
        ],
      },
      {
        heading: 'Children',
        paragraphs: [
          'The Service is not directed to children under 13 (or the higher age required in your jurisdiction). If you believe a child has provided personal data, contact us via Privacy controls so we can delete it.',
        ],
      },
      {
        heading: 'Changes',
        paragraphs: [
          'We may update this Privacy Policy as the product and providers change. Material updates will be posted on this page with a new “Last updated” date.',
        ],
      },
      {
        heading: 'Contact',
        paragraphs: [
          'For privacy requests, open Privacy controls in the product. Additional operator contact details will be published there as ExploreAI commercializes.',
        ],
      },
    ],
  },
  'cookie-policy': {
    slug: 'cookie-policy',
    title: 'Cookie Policy',
    summary: 'Necessary identity cookies and optional analytics technologies.',
    subtitle: 'Cookies and similar technologies used by ExploreAI',
    updated: 'Last updated: 2026-08-09',
    sections: [
      {
        heading: 'Necessary cookies',
        paragraphs: [
          'Client Identity is an HttpOnly cookie that scopes chat sessions and related data to your browser. It is required for session isolation and Owner Key style separation. It is not used for advertising.',
        ],
      },
      {
        heading: 'Optional analytics',
        paragraphs: [
          'If you accept analytics, we may load Datadog RUM and LaunchDarkly (or equivalent) for product analytics and feature flags. You can change this preference anytime on Privacy controls.',
        ],
      },
      {
        heading: 'Local storage',
        paragraphs: [
          'Consent preferences and certain client-only settings (for example pinned chat sessions) may be stored in localStorage or sessionStorage on your device. Clearing site data resets consent and local preferences.',
        ],
      },
      {
        heading: 'More information',
        paragraphs: [
          'For how personal data is processed beyond cookies, see the Privacy Policy. For third parties that may receive analytics events, see Sub-processors.',
        ],
      },
    ],
  },
  subprocessors: {
    slug: 'subprocessors',
    title: 'Sub-processors',
    summary: 'Third parties that may process data to deliver the service.',
    subtitle: 'Third parties that may process data to deliver ExploreAI',
    updated: 'Last updated: 2026-08-09',
    sections: [
      {
        heading: 'LLM and search providers',
        paragraphs: [
          'Configured chat, completion, embedding, and optional search providers process prompts, retrieved context, and related metadata to generate replies and tool results for your session.',
        ],
      },
      {
        heading: 'Hosting and delivery',
        paragraphs: [
          'Application hosting, CDN, and related infrastructure providers process connection metadata and application traffic for the deployed environment.',
        ],
      },
      {
        heading: 'Observability (optional)',
        paragraphs: [
          'If analytics consent is granted, Datadog may receive front-end RUM events. LaunchDarkly may receive flag evaluation events for feature management.',
        ],
      },
      {
        heading: 'Updates',
        paragraphs: [
          'This list is a commercialization draft and will be updated as providers are contracted. Material changes will be reflected on this page and cross-referenced from the Privacy Policy.',
        ],
      },
    ],
  },
};

const ZH: Record<PolicySlug, PolicyDocCopy> = {
  'terms-of-use': {
    slug: 'terms-of-use',
    title: '使用条款',
    summary: '使用规则、账号、内容与免责说明。',
    subtitle: '约束 ExploreAI 服务使用的协议',
    updated: '最近更新：2026-08-09',
    sections: [
      {
        heading: '协议',
        paragraphs: [
          '本《使用条款》（“条款”）适用于访问和使用 ExploreAI（“服务”），包括产品中提供的聊天、检索、生成及相关工具。',
          '访问或使用服务即表示你同意本条款。如不同意，请勿使用服务。本文档为产品商业化阶段草稿，不构成法律意见。',
        ],
      },
      {
        heading: '资格',
        paragraphs: [
          '你须具备适用法律下订立有约束力协议的能力。若你代表组织使用服务，即表示你有权使该组织受本条款约束。',
        ],
      },
      {
        heading: '账号与身份',
        paragraphs: [
          '服务可作为访客使用（浏览器范围的客户端身份），并在启用时可支持可选登录账号。',
          '你须对身份或账号下的活动负责，并妥善保管访问凭证与设备。',
        ],
      },
      {
        heading: '可接受使用',
        paragraphs: [
          '你仅可在遵守本条款与适用法律的前提下使用服务。不得滥用服务、规避速率或套餐限制、提交违法或有害内容、干扰其他用户，或试图访问不属于你的数据。',
          '我们可暂停或限制损害服务、其他用户或第三方，或违反本条款的访问。',
        ],
      },
      {
        heading: '你的内容与模型提供方',
        paragraphs: [
          '你保留所提交内容的权利。你授予 ExploreAI 有限许可，以便为运营、保障与改进服务而处理该内容，包括将提示与上下文传输至已配置的模型与工具提供方。',
          '请勿提交无权分享的内容，或你不希望由第三方模型提供方处理的敏感个人信息。',
        ],
      },
      {
        heading: '输出、相似性与非专业建议',
        paragraphs: [
          '输出由机器学习模型生成，可能不准确、不完整，或与其他用户的输出相似。依赖前请自行审阅。',
          '服务不提供法律、医疗、财务或其他专业建议。请勿将输出作为安全关键或受监管决策的唯一依据。',
        ],
      },
      {
        heading: '第三方服务',
        paragraphs: [
          '服务依赖第三方托管、模型、搜索与可观测性提供方。其条款与隐私实践适用于其处理活动。当前名单见「子处理方」页面。',
        ],
      },
      {
        heading: '反馈',
        paragraphs: [
          '若你提供反馈或建议，即授予 ExploreAI 在无限制、无补偿的情况下使用该反馈的权利。',
        ],
      },
      {
        heading: '中止与终止',
        paragraphs: [
          '我们可因违反本条款、服务风险，或运营/法律原因暂停或终止访问。你可随时停止使用服务。依其性质应继续有效的条款在终止后仍然有效。',
        ],
      },
      {
        heading: '免责声明',
        paragraphs: [
          '服务按“现状”和“可用”基础提供。在法律允许的最大范围内，ExploreAI 不作适销性、特定用途适用性及不侵权等保证。',
          '我们不保证服务不中断、无错误、无有害组件，或不保证输出满足你的要求。',
        ],
      },
      {
        heading: '责任限制',
        paragraphs: [
          '在法律允许的最大范围内，ExploreAI 及其供应商不对因使用服务产生的间接、附带、特殊、后果性或惩罚性损害，或利润、数据、商誉损失承担责任。',
          '与服务相关的索赔的累计责任以你在索赔前三个月内向我们支付的服务费用，或一百美元（或当地等值，若未付费）二者中较高者为限。',
        ],
      },
      {
        heading: '变更',
        paragraphs: [
          '我们可能随产品演进更新本条款。重大变更将在本页反映并更新日期。变更生效后继续使用即视为接受修订条款。',
        ],
      },
      {
        heading: '联系',
        paragraphs: [
          '有关本条款的问题，请使用产品中的「隐私控制」页。运营商联系方式将在服务商业化过程中于该页公布。',
        ],
      },
    ],
  },
  'privacy-policy': {
    slug: 'privacy-policy',
    title: '隐私政策',
    summary: '我们处理哪些数据、为何处理，以及你的选择。',
    subtitle: 'ExploreAI 如何处理个人数据',
    updated: '最近更新：2026-08-09',
    sections: [
      {
        heading: '我们是谁',
        paragraphs: [
          'ExploreAI（“我们”）提供 AI 聊天及相关工具。本隐私政策说明你在使用服务时我们如何处理个人数据。',
          '本文档为产品商业化阶段草稿，不构成法律意见。交互式偏好与擦除工具见「隐私控制」页。',
        ],
      },
      {
        heading: '我们处理的数据',
        paragraphs: [
          '视你的使用方式，我们可能处理：客户端身份或账号标识；聊天消息、上传及相关会话元数据；在你同意时的可选分析与功能开关事件；以及安全与可靠性所需的技术日志。',
          '请勿提交你不希望由模型或基础设施提供方处理的敏感个人信息。',
        ],
      },
      {
        heading: '处理目的',
        paragraphs: [
          '我们处理数据以提供并保障服务、按所有者或浏览器身份隔离会话、生成模型回复、记住你选择的偏好、在启用分析时衡量可靠性，以及遵守法律。',
        ],
      },
      {
        heading: '共享与子处理方',
        paragraphs: [
          '我们与帮助交付服务的子处理方共享数据，例如模型提供方、托管与可选可观测性供应商。我们不出售个人数据。',
          '提供方类别见「子处理方」页。视集成方式，其可能作为独立控制者或我们的处理者，并适用其自身条款。',
        ],
      },
      {
        heading: '保留与擦除',
        paragraphs: [
          '不活跃会话与过期运营数据按保留计划清理（大约九十天量级，除非安全或法律要求更长）。',
          '你可在「隐私控制」擦除本浏览器的聊天会话并轮换客户端身份。登录账号删除（若可用）将在该页说明。',
        ],
      },
      {
        heading: 'Cookie 与类似技术',
        paragraphs: [
          '我们使用必要的客户端身份 Cookie 将会话限定于你的浏览器。可选分析技术仅在你接受分析时加载。详见 Cookie 政策。',
        ],
      },
      {
        heading: '你的选择与权利',
        paragraphs: [
          '视所在地，你可能享有访问、更正、删除或限制处理个人数据，或反对某些处理的权利。产品内擦除与同意变更请使用「隐私控制」。',
          '若无法在产品内完成请求，请通过服务商业化后在「隐私控制」公布的渠道联系我们。',
        ],
      },
      {
        heading: '国际传输',
        paragraphs: [
          '模型与基础设施提供方可能在其运营地区处理数据。在需要时，我们依赖其提供的适当传输机制或适用法律。',
        ],
      },
      {
        heading: '儿童',
        paragraphs: [
          '服务不面向 13 岁以下儿童（或你所在司法辖区要求的更高年龄）。若你认为儿童提供了个人数据，请通过「隐私控制」联系我们以便删除。',
        ],
      },
      {
        heading: '变更',
        paragraphs: [
          '我们可能随产品与提供方变化更新本隐私政策。重大更新将发布于本页并更新「最近更新」日期。',
        ],
      },
      {
        heading: '联系',
        paragraphs: [
          '隐私相关请求请打开产品中的「隐私控制」。更多运营商联系方式将在 ExploreAI 商业化过程中于该页公布。',
        ],
      },
    ],
  },
  'cookie-policy': {
    slug: 'cookie-policy',
    title: 'Cookie 政策',
    summary: '必要身份 Cookie 与可选分析技术。',
    subtitle: 'ExploreAI 使用的 Cookie 与类似技术',
    updated: '最近更新：2026-08-09',
    sections: [
      {
        heading: '必要 Cookie',
        paragraphs: [
          '客户端身份是 HttpOnly Cookie，用于将聊天会话及相关数据限定于你的浏览器，服务于会话隔离与 Owner Key 式分离，不用于广告。',
        ],
      },
      {
        heading: '可选分析',
        paragraphs: [
          '若你接受分析，我们可能加载 Datadog RUM 与 LaunchDarkly（或同等技术）用于产品分析与功能开关。你可随时在「隐私控制」更改该偏好。',
        ],
      },
      {
        heading: '本地存储',
        paragraphs: [
          '同意偏好及部分仅客户端设置（例如已固定的聊天会话）可能存储在设备的 localStorage 或 sessionStorage。清除站点数据会重置同意与本地偏好。',
        ],
      },
      {
        heading: '更多信息',
        paragraphs: [
          'Cookie 之外的个人数据处理见隐私政策。可能接收分析事件的第三方见「子处理方」。',
        ],
      },
    ],
  },
  subprocessors: {
    slug: 'subprocessors',
    title: '子处理方',
    summary: '为提供服务可能处理数据的第三方。',
    subtitle: '为交付 ExploreAI 可能处理数据的第三方',
    updated: '最近更新：2026-08-09',
    sections: [
      {
        heading: '大模型与搜索提供方',
        paragraphs: [
          '已配置的聊天、补全、嵌入与可选搜索提供方会处理提示、检索上下文及相关元数据，以生成你会话中的回复与工具结果。',
        ],
      },
      {
        heading: '托管与交付',
        paragraphs: [
          '应用托管、CDN 及相关基础设施提供方会处理连接元数据与应用流量，以支撑已部署环境。',
        ],
      },
      {
        heading: '可观测性（可选）',
        paragraphs: [
          '在授予分析同意时，Datadog 可能接收前端 RUM 事件；LaunchDarkly 可能接收功能开关评估事件。',
        ],
      },
      {
        heading: '更新',
        paragraphs: [
          '本名单为商业化草稿，将随供应商签约更新。重大变更将反映于本页，并由隐私政策交叉引用。',
        ],
      },
    ],
  },
};

const JA: Record<PolicySlug, PolicyDocCopy> = {
  'terms-of-use': {
    slug: 'terms-of-use',
    title: '利用規約',
    summary: '利用ルール、アカウント、コンテンツ、免責。',
    subtitle: 'ExploreAI サービス利用に関する合意',
    updated: '最終更新: 2026-08-09',
    sections: [
      {
        heading: '合意',
        paragraphs: [
          '本利用規約（「本規約」）は、ExploreAI（「本サービス」）へのアクセスおよび利用（チャット、検索、生成、関連ツールを含む）を規律します。',
          '本サービスにアクセスまたは利用することで、本規約に同意したものとみなされます。同意しない場合は利用しないでください。本稿は商用化向けの草案であり、法的助言ではありません。',
        ],
      },
      {
        heading: '利用資格',
        paragraphs: [
          '適用法の下で拘束力のある契約を締結できる必要があります。組織を代表して利用する場合、当該組織を本規約に拘束する権限があることを表明します。',
        ],
      },
      {
        heading: 'アカウントと識別子',
        paragraphs: [
          '本サービスはブラウザ範囲のクライアント識別子によるゲスト利用が可能で、有効化時には任意のサインインアカウントにも対応します。',
          '識別子またはアカウント上の活動、および認証情報・端末の安全管理は利用者の責任です。',
        ],
      },
      {
        heading: '許容される利用',
        paragraphs: [
          '本規約および適用法に従ってのみ利用できます。乱用、制限回避、違法・有害コンテンツの送信、他利用者への妨害、他人のデータへの不正アクセスは禁止です。',
          '本サービス、他利用者、第三者に害を及ぼす、または本規約に違反するアクセスは停止・制限する場合があります。',
        ],
      },
      {
        heading: 'コンテンツとモデル提供者',
        paragraphs: [
          '提出コンテンツの権利は利用者に帰属します。ExploreAI には、運営・保護・改善のために必要な範囲で処理する限定的なライセンスが付与され、設定済みのモデル／ツール提供者への送信を含みます。',
          '共有権限のない内容や、第三者モデル提供者に処理させたくない機微な個人データは送信しないでください。',
        ],
      },
      {
        heading: '出力、類似性、専門助言の否定',
        paragraphs: [
          '出力は機械学習モデルにより生成され、不正確・不完全、または他利用者向け出力と類似する場合があります。依拠前に自ら確認してください。',
          '本サービスは法律・医療・金融等の専門助言を提供しません。安全重要または規制対象の判断の唯一の根拠にしないでください。',
        ],
      },
      {
        heading: '第三者サービス',
        paragraphs: [
          '本サービスはホスティング、モデル、検索、オブザーバビリティ等の第三者に依存します。その処理には各提供者の規約とプライバシー慣行が適用されます。現行リストは委託先ページを参照してください。',
        ],
      },
      {
        heading: 'フィードバック',
        paragraphs: [
          'フィードバックや提案を提供した場合、ExploreAI は制限や対価なく利用できるものとします。',
        ],
      },
      {
        heading: '停止と終了',
        paragraphs: [
          '本規約違反、サービスリスク、運用上または法的理由によりアクセスを停止・終了できます。利用者はいつでも利用を止められます。性質上存続すべき条項は終了後も有効です。',
        ],
      },
      {
        heading: '免責',
        paragraphs: [
          '本サービスは「現状有姿」「提供可能な範囲」で提供されます。法が許す最大限の範囲で、商品性・特定目的適合性・非侵害の保証を否認します。',
          '中断・エラー・有害要素のないこと、または出力が要件を満たすことは保証しません。',
        ],
      },
      {
        heading: '責任制限',
        paragraphs: [
          '法が許す最大限の範囲で、ExploreAI およびサプライヤーは、間接・付随・特別・結果・懲罰的損害、または利益・データ・信用の損失について責任を負いません。',
          '本サービスに関する請求の合計責任は、請求前 3 か月に支払った利用料、または未払いの場合は 100 米ドル（または現地相当額）のいずれか高い額を上限とします。',
        ],
      },
      {
        heading: '変更',
        paragraphs: [
          '製品の進化に伴い本規約を更新する場合があります。重要な変更は本ページに反映し日付を更新します。効力発生後の継続利用は改訂規約への同意となります。',
        ],
      },
      {
        heading: '連絡先',
        paragraphs: [
          '本規約に関する質問は製品内のプライバシー設定ページをご利用ください。事業者の連絡先は商用化に伴い同ページに掲載します。',
        ],
      },
    ],
  },
  'privacy-policy': {
    slug: 'privacy-policy',
    title: 'プライバシーポリシー',
    summary: '処理するデータ、目的、選択肢。',
    subtitle: 'ExploreAI による個人データの取扱い',
    updated: '最終更新: 2026-08-09',
    sections: [
      {
        heading: '運営者',
        paragraphs: [
          'ExploreAI（「当社」）は AI チャットおよび関連ツールを提供します。本ポリシーは本サービス利用時の個人データ処理について説明します。',
          '本稿は商用化向け草案であり法的助言ではありません。設定と消去ツールはプライバシー設定ページで利用できます。',
        ],
      },
      {
        heading: '処理するデータ',
        paragraphs: [
          '利用状況に応じて、クライアント識別子またはアカウント識別子、チャットメッセージ・アップロード・セッションメタデータ、同意時の任意の分析／機能フラグイベント、セキュリティと信頼性のための技術ログを処理する場合があります。',
          'モデルやインフラ提供者に処理させたくない機微な個人データは送信しないでください。',
        ],
      },
      {
        heading: '目的',
        paragraphs: [
          'サービス提供と保護、所有者／ブラウザ識別子によるセッション分離、モデル応答生成、選択した設定の保持、分析有効時の信頼性測定、法令遵守のために処理します。',
        ],
      },
      {
        heading: '共有と委託先',
        paragraphs: [
          'モデル提供者、ホスティング、任意のオブザーバビリティベンダーなど、サービス提供を支援する委託先とデータを共有します。個人データは販売しません。',
          '提供者の区分は委託先ページを参照してください。統合により独立の管理者または当社の処理者として、各提供者の条件が適用されます。',
        ],
      },
      {
        heading: '保管と消去',
        paragraphs: [
          '非アクティブなセッションや古い運用データは保管スケジュール（おおよそ 90 日程度。セキュリティや法令でより長い期間が必要な場合を除く）に従い削除されます。',
          'プライバシー設定から本ブラウザのチャットセッション消去とクライアント識別子の再発行が可能です。サインインアカウント削除が可能な場合は同ページに記載します。',
        ],
      },
      {
        heading: 'Cookie 等の技術',
        paragraphs: [
          'セッションをブラウザに紐づけるために必要なクライアント識別 Cookie を使用します。任意の分析技術は分析に同意した場合のみ読み込みます。詳細は Cookie ポリシーを参照してください。',
        ],
      },
      {
        heading: '選択と権利',
        paragraphs: [
          '所在地により、個人データへのアクセス・訂正・削除・制限、または特定の処理への異議申立ての権利がある場合があります。製品内の消去と同意変更はプライバシー設定をご利用ください。',
          '製品内で完了できない場合は、商用化に伴いプライバシー設定に掲載する連絡先へご連絡ください。',
        ],
      },
      {
        heading: '国際転送',
        paragraphs: [
          'モデルおよびインフラ提供者は、運用地域でデータを処理する場合があります。必要な場合は、提供者または適用法に基づく適切な転送メカニズムに依拠します。',
        ],
      },
      {
        heading: '子ども',
        paragraphs: [
          '本サービスは 13 歳未満（または管轄で求められるより高い年齢）の子どもを対象としません。子どもが個人データを提供したと思われる場合は、プライバシー設定から連絡してください。削除対応します。',
        ],
      },
      {
        heading: '変更',
        paragraphs: [
          '製品や提供者の変更に伴い本ポリシーを更新する場合があります。重要な更新は本ページに掲載し「最終更新」日を更新します。',
        ],
      },
      {
        heading: '連絡先',
        paragraphs: [
          'プライバシーに関する請求は製品内のプライバシー設定を開いてください。追加の事業者連絡先は商用化に伴い同ページに掲載します。',
        ],
      },
    ],
  },
  'cookie-policy': {
    slug: 'cookie-policy',
    title: 'Cookie ポリシー',
    summary: '必要な識別 Cookie と任意の分析技術。',
    subtitle: 'ExploreAI が使用する Cookie および類似技術',
    updated: '最終更新: 2026-08-09',
    sections: [
      {
        heading: '必要な Cookie',
        paragraphs: [
          'クライアント識別子は HttpOnly Cookie で、チャットセッション等をブラウザに紐づけます。セッション分離と Owner Key 型分離に必要であり、広告には使用しません。',
        ],
      },
      {
        heading: '任意の分析',
        paragraphs: [
          '分析に同意した場合、製品分析と機能フラグのために Datadog RUM および LaunchDarkly（または同等）を読み込むことがあります。設定はプライバシー設定でいつでも変更できます。',
        ],
      },
      {
        heading: 'ローカルストレージ',
        paragraphs: [
          '同意設定や一部のクライアント専用設定（固定したチャットなど）は端末の localStorage / sessionStorage に保存される場合があります。サイトデータを消去すると同意とローカル設定がリセットされます。',
        ],
      },
      {
        heading: '詳細情報',
        paragraphs: [
          'Cookie 以外の個人データ処理はプライバシーポリシーを、分析イベントを受け取る可能性のある第三者は委託先を参照してください。',
        ],
      },
    ],
  },
  subprocessors: {
    slug: 'subprocessors',
    title: '委託先',
    summary: 'サービス提供のためにデータを処理し得る第三者。',
    subtitle: 'ExploreAI 提供のためにデータを処理し得る第三者',
    updated: '最終更新: 2026-08-09',
    sections: [
      {
        heading: 'LLM および検索提供者',
        paragraphs: [
          '設定済みのチャット、補完、埋め込み、任意の検索提供者は、プロンプト・取得コンテキスト・関連メタデータを処理し、セッション向けの応答とツール結果を生成します。',
        ],
      },
      {
        heading: 'ホスティングと配信',
        paragraphs: [
          'アプリケーションホスティング、CDN、関連インフラ提供者は、デプロイ環境のため接続メタデータとアプリケーショントラフィックを処理します。',
        ],
      },
      {
        heading: 'オブザーバビリティ（任意）',
        paragraphs: [
          '分析同意がある場合、Datadog はフロントエンド RUM イベントを、LaunchDarkly は機能管理のためのフラグ評価イベントを受信する場合があります。',
        ],
      },
      {
        heading: '更新',
        paragraphs: [
          '本リストは商用化草案であり、契約進展に伴い更新します。重要な変更は本ページに反映し、プライバシーポリシーからも参照します。',
        ],
      },
    ],
  },
};

const FR: Record<PolicySlug, PolicyDocCopy> = {
  'terms-of-use': {
    slug: 'terms-of-use',
    title: 'Conditions d\'utilisation',
    summary: 'Règles d\'usage, comptes, contenus et exclusions de garantie.',
    subtitle: 'Accord régissant l\'utilisation du service ExploreAI',
    updated: 'Dernière mise à jour : 2026-08-09',
    sections: [
      {
        heading: 'Accord',
        paragraphs: [
          'Les présentes Conditions d\'utilisation (« Conditions ») régissent l\'accès et l\'utilisation d\'ExploreAI (le « Service »), y compris le chat, la recherche, la génération et les outils associés.',
          'En accédant au Service ou en l\'utilisant, vous acceptez ces Conditions. Sinon, n\'utilisez pas le Service. Ce document est un brouillon de commercialisation et ne remplace pas un avis juridique.',
        ],
      },
      {
        heading: 'Éligibilité',
        paragraphs: [
          'Vous devez pouvoir conclure un contrat contraignant selon le droit applicable. Si vous utilisez le Service pour une organisation, vous déclarez avoir l\'autorité de l\'engager.',
        ],
      },
      {
        heading: 'Comptes et identité',
        paragraphs: [
          'Le Service peut être utilisé en invité avec une identité client liée au navigateur, et peut aussi prendre en charge des comptes connectés optionnels lorsqu\'ils sont activés.',
          'Vous êtes responsable de l\'activité sous votre identité ou compte et de la sécurité de vos identifiants et appareils.',
        ],
      },
      {
        heading: 'Usage acceptable',
        paragraphs: [
          'Vous n\'utilisez le Service qu\'en conformité avec ces Conditions et la loi. Il est interdit d\'abuser du Service, de contourner les limites, de soumettre des contenus illicites ou nuisibles, de perturber d\'autres utilisateurs ou d\'accéder à des données qui ne vous appartiennent pas.',
          'Nous pouvons suspendre ou limiter un accès qui nuit au Service, aux utilisateurs ou à des tiers, ou qui viole ces Conditions.',
        ],
      },
      {
        heading: 'Votre contenu et fournisseurs de modèles',
        paragraphs: [
          'Vous conservez vos droits sur le contenu soumis. Vous accordez à ExploreAI une licence limitée pour le traiter afin d\'exploiter, sécuriser et améliorer le Service, y compris la transmission aux fournisseurs de modèles et d\'outils configurés.',
          'Ne soumettez pas de contenu que vous n\'êtes pas autorisé à partager, ni de données personnelles sensibles que vous ne souhaitez pas faire traiter par des tiers.',
        ],
      },
      {
        heading: 'Sorties, similarité et absence de conseil professionnel',
        paragraphs: [
          'Les sorties sont générées par des modèles d\'apprentissage automatique et peuvent être inexactes, incomplètes ou similaires à celles d\'autres utilisateurs. Vérifiez-les avant de vous y fier.',
          'Le Service ne fournit pas de conseil juridique, médical, financier ou professionnel. N\'en faites pas la seule base de décisions critiques ou réglementées.',
        ],
      },
      {
        heading: 'Services tiers',
        paragraphs: [
          'Le Service dépend d\'hébergeurs, modèles, recherche et observabilité tiers. Leurs conditions et pratiques de confidentialité s\'appliquent. Voir la page Sous-traitants pour la liste actuelle.',
        ],
      },
      {
        heading: 'Commentaires',
        paragraphs: [
          'Si vous fournissez des commentaires ou suggestions, vous autorisez ExploreAI à les utiliser sans restriction ni compensation.',
        ],
      },
      {
        heading: 'Suspension et résiliation',
        paragraphs: [
          'Nous pouvons suspendre ou résilier l\'accès en cas de violation, de risque pour le Service, ou pour des raisons opérationnelles ou légales. Vous pouvez cesser d\'utiliser le Service à tout moment. Les dispositions destinées à survivre demeurent applicables.',
        ],
      },
      {
        heading: 'Avertissements',
        paragraphs: [
          'LE SERVICE EST FOURNI « EN L\'ÉTAT » ET « SELON DISPONIBILITÉ ». DANS LA MESURE MAXIMALE PERMISE PAR LA LOI, EXPLOREAI EXCLUT LES GARANTIES DE QUALITÉ MARCHANDE, D\'ADÉQUATION À UN USAGE PARTICULIER ET DE NON-CONTREFAÇON.',
          'Nous ne garantissons pas un Service ininterrompu, sans erreur ni composants nuisibles, ni que les sorties répondront à vos besoins.',
        ],
      },
      {
        heading: 'Limitation de responsabilité',
        paragraphs: [
          'Dans la mesure maximale permise par la loi, ExploreAI et ses fournisseurs ne sont pas responsables des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs, ni des pertes de profits, de données ou de clientèle.',
          'La responsabilité globale pour les réclamations liées au Service est limitée au plus élevé des frais payés pour le Service au cours des trois mois précédant la réclamation, ou cent dollars US (ou équivalent local) en l\'absence de frais.',
        ],
      },
      {
        heading: 'Modifications',
        paragraphs: [
          'Nous pouvons mettre à jour ces Conditions. Les changements importants figureront sur cette page avec une date actualisée. L\'usage continu après entrée en vigueur vaut acceptation.',
        ],
      },
      {
        heading: 'Contact',
        paragraphs: [
          'Pour toute question, utilisez la page Contrôles de confidentialité du produit. Les coordonnées de l\'opérateur y seront publiées lors de la commercialisation.',
        ],
      },
    ],
  },
  'privacy-policy': {
    slug: 'privacy-policy',
    title: 'Politique de confidentialité',
    summary: 'Données traitées, finalités et vos choix.',
    subtitle: 'Comment ExploreAI traite les données personnelles',
    updated: 'Dernière mise à jour : 2026-08-09',
    sections: [
      {
        heading: 'Qui nous sommes',
        paragraphs: [
          'ExploreAI (« nous ») fournit un chat IA et des outils associés. La présente politique explique le traitement des données personnelles lors de l\'utilisation du Service.',
          'Document brouillon de commercialisation, non substitut à un avis juridique. Préférences et effacement sont disponibles via Contrôles de confidentialité.',
        ],
      },
      {
        heading: 'Données traitées',
        paragraphs: [
          'Selon l\'usage, nous pouvons traiter : identité client ou identifiants de compte ; messages, téléversements et métadonnées de session ; événements d\'analytique et de flags si vous consentez ; journaux techniques de sécurité et fiabilité.',
          'Ne soumettez pas de données personnelles sensibles que vous ne souhaitez pas faire traiter par des fournisseurs de modèles ou d\'infrastructure.',
        ],
      },
      {
        heading: 'Finalités',
        paragraphs: [
          'Nous traitons les données pour fournir et sécuriser le Service, isoler les sessions par propriétaire ou identité navigateur, générer des réponses, mémoriser vos préférences, mesurer la fiabilité si l\'analytique est activée, et respecter la loi.',
        ],
      },
      {
        heading: 'Partage et sous-traitants',
        paragraphs: [
          'Nous partageons des données avec des sous-traitants (modèles, hébergement, observabilité optionnelle). Nous ne vendons pas de données personnelles.',
          'Voir la page Sous-traitants. Selon l\'intégration, ces fournisseurs agissent comme responsables indépendants ou comme nos sous-traitants.',
        ],
      },
      {
        heading: 'Conservation et effacement',
        paragraphs: [
          'Les sessions inactives et données opérationnelles anciennes sont purgées selon un calendrier (environ quatre-vingt-dix jours, sauf exigence plus longue).',
          'Vous pouvez effacer les sessions de ce navigateur et renouveler l\'identité client via Contrôles de confidentialité. La suppression de compte connecté, le cas échéant, sera décrite sur cette page.',
        ],
      },
      {
        heading: 'Cookies et technologies similaires',
        paragraphs: [
          'Nous utilisons un cookie d\'identité client nécessaire pour lier les sessions à votre navigateur. Les technologies d\'analytique optionnelles ne se chargent qu\'avec votre accord. Détails dans la Politique de cookies.',
        ],
      },
      {
        heading: 'Vos choix et droits',
        paragraphs: [
          'Selon votre lieu, vous pouvez avoir des droits d\'accès, de rectification, d\'effacement, de limitation ou d\'opposition. Utilisez Contrôles de confidentialité pour l\'effacement et le consentement dans le produit.',
          'Si une demande ne peut être traitée dans le produit, contactez-nous via le canal publié sur Contrôles de confidentialité lors de la commercialisation.',
        ],
      },
      {
        heading: 'Transferts internationaux',
        paragraphs: [
          'Les fournisseurs de modèles et d\'infrastructure peuvent traiter des données dans les régions où ils opèrent. Le cas échéant, nous nous appuyons sur des mécanismes de transfert appropriés.',
        ],
      },
      {
        heading: 'Enfants',
        paragraphs: [
          'Le Service ne s\'adresse pas aux enfants de moins de 13 ans (ou l\'âge plus élevé requis). Si un enfant a fourni des données, contactez-nous via Contrôles de confidentialité pour suppression.',
        ],
      },
      {
        heading: 'Modifications',
        paragraphs: [
          'Nous pouvons mettre à jour cette politique. Les mises à jour importantes seront publiées ici avec une nouvelle date « Dernière mise à jour ».',
        ],
      },
      {
        heading: 'Contact',
        paragraphs: [
          'Pour les demandes de confidentialité, ouvrez Contrôles de confidentialité. Des coordonnées supplémentaires y seront publiées lors de la commercialisation.',
        ],
      },
    ],
  },
  'cookie-policy': {
    slug: 'cookie-policy',
    title: 'Politique de cookies',
    summary: 'Cookies d\'identité nécessaires et analytics optionnels.',
    subtitle: 'Cookies et technologies similaires utilisés par ExploreAI',
    updated: 'Dernière mise à jour : 2026-08-09',
    sections: [
      {
        heading: 'Cookies nécessaires',
        paragraphs: [
          'L\'identité client est un cookie HttpOnly qui lie les sessions de chat à votre navigateur. Elle est requise pour l\'isolation des sessions et n\'est pas utilisée pour la publicité.',
        ],
      },
      {
        heading: 'Analytique optionnelle',
        paragraphs: [
          'Si vous acceptez l\'analytique, nous pouvons charger Datadog RUM et LaunchDarkly (ou équivalent). Vous pouvez modifier ce choix à tout moment dans Contrôles de confidentialité.',
        ],
      },
      {
        heading: 'Stockage local',
        paragraphs: [
          'Les préférences de consentement et certains réglages client (ex. sessions épinglées) peuvent être stockés en localStorage ou sessionStorage. Effacer les données du site réinitialise consentement et préférences locales.',
        ],
      },
      {
        heading: 'Plus d\'informations',
        paragraphs: [
          'Pour le traitement des données au-delà des cookies, voir la Politique de confidentialité. Pour les tiers susceptibles de recevoir des événements d\'analytique, voir Sous-traitants.',
        ],
      },
    ],
  },
  subprocessors: {
    slug: 'subprocessors',
    title: 'Sous-traitants',
    summary: 'Tiers susceptibles de traiter des données pour le service.',
    subtitle: 'Tiers susceptibles de traiter des données pour ExploreAI',
    updated: 'Dernière mise à jour : 2026-08-09',
    sections: [
      {
        heading: 'Fournisseurs LLM et recherche',
        paragraphs: [
          'Les fournisseurs de chat, complétion, embeddings et recherche optionnelle configurés traitent invites, contexte récupéré et métadonnées pour générer réponses et résultats d\'outils.',
        ],
      },
      {
        heading: 'Hébergement et diffusion',
        paragraphs: [
          'Les fournisseurs d\'hébergement, CDN et infrastructure traitent métadonnées de connexion et trafic applicatif pour l\'environnement déployé.',
        ],
      },
      {
        heading: 'Observabilité (optionnelle)',
        paragraphs: [
          'Avec consentement analytique, Datadog peut recevoir des événements RUM frontaux. LaunchDarkly peut recevoir des évaluations de flags.',
        ],
      },
      {
        heading: 'Mises à jour',
        paragraphs: [
          'Cette liste est un brouillon de commercialisation et sera mise à jour au fil des contrats. Les changements importants figureront ici et dans la Politique de confidentialité.',
        ],
      },
    ],
  },
};

const ES: Record<PolicySlug, PolicyDocCopy> = {
  'terms-of-use': {
    slug: 'terms-of-use',
    title: 'Términos de uso',
    summary: 'Reglas de uso, cuentas, contenido y exenciones.',
    subtitle: 'Acuerdo que rige el uso del servicio ExploreAI',
    updated: 'Última actualización: 2026-08-09',
    sections: [
      {
        heading: 'Acuerdo',
        paragraphs: [
          'Estos Términos de uso («Términos») rigen el acceso y uso de ExploreAI (el «Servicio»), incluidos chat, recuperación, generación y herramientas relacionadas.',
          'Al acceder o usar el Servicio, aceptas estos Términos. Si no estás de acuerdo, no uses el Servicio. Este documento es un borrador de comercialización y no sustituye asesoría legal.',
        ],
      },
      {
        heading: 'Elegibilidad',
        paragraphs: [
          'Debes poder celebrar un contrato vinculante según la ley aplicable. Si usas el Servicio en nombre de una organización, declaras tener autoridad para vincularla.',
        ],
      },
      {
        heading: 'Cuentas e identidad',
        paragraphs: [
          'El Servicio puede usarse como invitado con una Identidad de Cliente limitada al navegador y, cuando esté habilitado, con cuentas opcionales.',
          'Eres responsable de la actividad bajo tu identidad o cuenta y de proteger credenciales y dispositivos.',
        ],
      },
      {
        heading: 'Uso aceptable',
        paragraphs: [
          'Solo puedes usar el Servicio conforme a estos Términos y la ley. No abuses del Servicio, eludas límites, envíes contenido ilícito o dañino, interfieras con otros usuarios ni intentes acceder a datos ajenos.',
          'Podemos suspender o limitar el acceso que dañe el Servicio, a usuarios o terceros, o que vulnere estos Términos.',
        ],
      },
      {
        heading: 'Tu contenido y proveedores de modelos',
        paragraphs: [
          'Conservas los derechos sobre el contenido que envías. Otorgas a ExploreAI una licencia limitada para procesarlo a fin de operar, proteger y mejorar el Servicio, incluida la transmisión a proveedores de modelos y herramientas configurados.',
          'No envíes contenido que no puedas compartir ni datos personales sensibles que no quieras que procesen terceros.',
        ],
      },
      {
        heading: 'Resultados, similitud y ausencia de consejo profesional',
        paragraphs: [
          'Los resultados los generan modelos de aprendizaje automático y pueden ser inexactos, incompletos o similares a los de otros usuarios. Revísalos antes de confiar en ellos.',
          'El Servicio no ofrece consejo legal, médico, financiero u otro consejo profesional. No uses los resultados como única base de decisiones críticas o reguladas.',
        ],
      },
      {
        heading: 'Servicios de terceros',
        paragraphs: [
          'El Servicio depende de proveedores de alojamiento, modelos, búsqueda y observabilidad. Sus términos y prácticas de privacidad se aplican. Consulta Subencargados para la lista actual.',
        ],
      },
      {
        heading: 'Comentarios',
        paragraphs: [
          'Si proporcionas comentarios o sugerencias, autorizas a ExploreAI a usarlos sin restricción ni compensación.',
        ],
      },
      {
        heading: 'Suspensión y terminación',
        paragraphs: [
          'Podemos suspender o terminar el acceso por incumplimientos, riesgo para el Servicio o motivos operativos o legales. Puedes dejar de usar el Servicio en cualquier momento. Las cláusulas que deban sobrevivir seguirán vigentes.',
        ],
      },
      {
        heading: 'Exenciones',
        paragraphs: [
          'EL SERVICIO SE PROPORCIONA «TAL CUAL» Y «SEGÚN DISPONIBILIDAD». EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, EXPLOREAI RENUNCIA A GARANTÍAS DE COMERCIABILIDAD, IDONEIDAD PARA UN FIN PARTICULAR Y NO INFRACCIÓN.',
          'No garantizamos que el Servicio sea ininterrumpido, libre de errores o componentes dañinos, ni que los resultados cumplan tus requisitos.',
        ],
      },
      {
        heading: 'Limitación de responsabilidad',
        paragraphs: [
          'En la máxima medida permitida por la ley, ExploreAI y sus proveedores no serán responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos, ni de pérdida de beneficios, datos o clientela.',
          'La responsabilidad agregada se limita al mayor entre las tarifas pagadas por el Servicio en los tres meses anteriores a la reclamación o cien dólares estadounidenses (o equivalente local) si no se pagaron tarifas.',
        ],
      },
      {
        heading: 'Cambios',
        paragraphs: [
          'Podemos actualizar estos Términos. Los cambios materiales se reflejarán en esta página con fecha actualizada. El uso continuado tras la vigencia implica aceptación.',
        ],
      },
      {
        heading: 'Contacto',
        paragraphs: [
          'Para preguntas sobre estos Términos, usa Controles de privacidad en el producto. Los datos de contacto del operador se publicarán allí al comercializar el Servicio.',
        ],
      },
    ],
  },
  'privacy-policy': {
    slug: 'privacy-policy',
    title: 'Política de privacidad',
    summary: 'Qué datos tratamos, para qué y tus opciones.',
    subtitle: 'Cómo ExploreAI trata datos personales',
    updated: 'Última actualización: 2026-08-09',
    sections: [
      {
        heading: 'Quiénes somos',
        paragraphs: [
          'ExploreAI («nosotros») ofrece chat de IA y herramientas relacionadas. Esta Política explica cómo tratamos datos personales al usar el Servicio.',
          'Es un borrador de comercialización y no sustituye asesoría legal. Preferencias y borrado están en Controles de privacidad.',
        ],
      },
      {
        heading: 'Datos que tratamos',
        paragraphs: [
          'Según el uso, podemos tratar: Identidad de Cliente o identificadores de cuenta; mensajes, cargas y metadatos de sesión; eventos opcionales de analítica y flags si consientes; y registros técnicos de seguridad y fiabilidad.',
          'No envíes datos personales sensibles que no quieras que procesen proveedores de modelos o infraestructura.',
        ],
      },
      {
        heading: 'Finalidades',
        paragraphs: [
          'Tratamos datos para prestar y proteger el Servicio, aislar sesiones por propietario o identidad del navegador, generar respuestas, recordar preferencias, medir fiabilidad con analítica habilitada y cumplir la ley.',
        ],
      },
      {
        heading: 'Compartición y subencargados',
        paragraphs: [
          'Compartimos datos con subencargados que ayudan a prestar el Servicio (modelos, alojamiento, observabilidad opcional). No vendemos datos personales.',
          'Consulta Subencargados. Según la integración, actúan como responsables independientes o como nuestros encargados.',
        ],
      },
      {
        heading: 'Conservación y borrado',
        paragraphs: [
          'Las sesiones inactivas y datos operativos antiguos se purgan según un calendario (del orden de unos noventa días, salvo plazos mayores por seguridad o ley).',
          'Puedes borrar las sesiones de este navegador y rotar la Identidad de Cliente en Controles de privacidad. El borrado de cuenta, cuando exista, se describirá allí.',
        ],
      },
      {
        heading: 'Cookies y tecnologías similares',
        paragraphs: [
          'Usamos una cookie necesaria de Identidad de Cliente para vincular sesiones a tu navegador. La analítica opcional solo se carga si la aceptas. Detalles en la Política de cookies.',
        ],
      },
      {
        heading: 'Tus opciones y derechos',
        paragraphs: [
          'Según tu ubicación, puedes tener derechos de acceso, rectificación, eliminación, limitación u oposición. Usa Controles de privacidad para borrado y consentimiento en el producto.',
          'Si no puede completarse en el producto, contáctanos por el canal publicado en Controles de privacidad al comercializar el Servicio.',
        ],
      },
      {
        heading: 'Transferencias internacionales',
        paragraphs: [
          'Los proveedores de modelos e infraestructura pueden tratar datos en las regiones donde operan. Cuando corresponda, nos apoyamos en mecanismos de transferencia adecuados.',
        ],
      },
      {
        heading: 'Menores',
        paragraphs: [
          'El Servicio no está dirigido a menores de 13 años (o la edad superior exigida). Si crees que un menor aportó datos, contáctanos vía Controles de privacidad para eliminarlos.',
        ],
      },
      {
        heading: 'Cambios',
        paragraphs: [
          'Podemos actualizar esta Política. Las actualizaciones materiales se publicarán aquí con una nueva fecha de «Última actualización».',
        ],
      },
      {
        heading: 'Contacto',
        paragraphs: [
          'Para solicitudes de privacidad, abre Controles de privacidad. Se publicarán más datos de contacto del operador al comercializar ExploreAI.',
        ],
      },
    ],
  },
  'cookie-policy': {
    slug: 'cookie-policy',
    title: 'Política de cookies',
    summary: 'Cookies de identidad necesarias y analítica opcional.',
    subtitle: 'Cookies y tecnologías similares usadas por ExploreAI',
    updated: 'Última actualización: 2026-08-09',
    sections: [
      {
        heading: 'Cookies necesarias',
        paragraphs: [
          'La Identidad de Cliente es una cookie HttpOnly que vincula las sesiones de chat a tu navegador. Es necesaria para el aislamiento de sesiones y no se usa para publicidad.',
        ],
      },
      {
        heading: 'Analítica opcional',
        paragraphs: [
          'Si aceptas analítica, podemos cargar Datadog RUM y LaunchDarkly (o equivalentes). Puedes cambiar esta preferencia en Controles de privacidad en cualquier momento.',
        ],
      },
      {
        heading: 'Almacenamiento local',
        paragraphs: [
          'Las preferencias de consentimiento y ciertos ajustes solo de cliente (p. ej. sesiones fijadas) pueden guardarse en localStorage o sessionStorage. Borrar los datos del sitio restablece consentimiento y preferencias locales.',
        ],
      },
      {
        heading: 'Más información',
        paragraphs: [
          'Para el tratamiento de datos más allá de las cookies, consulta la Política de privacidad. Para terceros que puedan recibir eventos de analítica, consulta Subencargados.',
        ],
      },
    ],
  },
  subprocessors: {
    slug: 'subprocessors',
    title: 'Subencargados',
    summary: 'Terceros que pueden tratar datos para prestar el servicio.',
    subtitle: 'Terceros que pueden tratar datos para prestar ExploreAI',
    updated: 'Última actualización: 2026-08-09',
    sections: [
      {
        heading: 'Proveedores de LLM y búsqueda',
        paragraphs: [
          'Los proveedores configurados de chat, completion, embeddings y búsqueda opcional procesan prompts, contexto recuperado y metadatos para generar respuestas y resultados de herramientas.',
        ],
      },
      {
        heading: 'Alojamiento y entrega',
        paragraphs: [
          'Los proveedores de alojamiento, CDN e infraestructura procesan metadatos de conexión y tráfico de la aplicación para el entorno desplegado.',
        ],
      },
      {
        heading: 'Observabilidad (opcional)',
        paragraphs: [
          'Con consentimiento de analítica, Datadog puede recibir eventos RUM del front-end. LaunchDarkly puede recibir evaluaciones de flags.',
        ],
      },
      {
        heading: 'Actualizaciones',
        paragraphs: [
          'Esta lista es un borrador de comercialización y se actualizará al contratar proveedores. Los cambios materiales se reflejarán aquí y en la Política de privacidad.',
        ],
      },
    ],
  },
};

export const POLICY_DOCS: Record<Language, Record<PolicySlug, PolicyDocCopy>> = {
  en: EN,
  zh: ZH,
  ja: JA,
  fr: FR,
  es: ES,
};
