import type { Language } from '../core/i18n/translations.types';

export type LegalDocId = 'terms' | 'privacy' | 'cookies' | 'subprocessors';

export interface LegalDocCopy {
  title: string;
  subtitle: string;
  updated: string;
  sections: { heading: string; body: string }[];
}

export interface LegalHubCopy {
  title: string;
  subtitle: string;
  links: { id: LegalDocId; label: string }[];
  backToChat: string;
  controlsLink: string;
}

const HUB: Record<Language, LegalHubCopy> = {
  en: {
    title: 'Legal',
    subtitle: 'Terms, privacy, cookies, and sub-processors for ExploreAI',
    links: [
      { id: 'terms', label: 'Terms of Service' },
      { id: 'privacy', label: 'Privacy Policy' },
      { id: 'cookies', label: 'Cookie Policy' },
      { id: 'subprocessors', label: 'Sub-processors' },
    ],
    backToChat: 'Back to chat',
    controlsLink: 'Privacy controls',
  },
  zh: {
    title: '法律信息',
    subtitle: 'ExploreAI 的服务条款、隐私、Cookie 与子处理方说明',
    links: [
      { id: 'terms', label: '服务条款' },
      { id: 'privacy', label: '隐私政策' },
      { id: 'cookies', label: 'Cookie 政策' },
      { id: 'subprocessors', label: '子处理方' },
    ],
    backToChat: '返回对话',
    controlsLink: '隐私控制',
  },
  ja: {
    title: '法的情報',
    subtitle: 'ExploreAI の利用規約、プライバシー、Cookie、委託先',
    links: [
      { id: 'terms', label: '利用規約' },
      { id: 'privacy', label: 'プライバシーポリシー' },
      { id: 'cookies', label: 'Cookie ポリシー' },
      { id: 'subprocessors', label: '委託先' },
    ],
    backToChat: 'チャットへ戻る',
    controlsLink: 'プライバシー設定',
  },
  fr: {
    title: 'Mentions légales',
    subtitle: 'Conditions, confidentialité, cookies et sous-traitants ExploreAI',
    links: [
      { id: 'terms', label: 'Conditions d\'utilisation' },
      { id: 'privacy', label: 'Politique de confidentialité' },
      { id: 'cookies', label: 'Politique de cookies' },
      { id: 'subprocessors', label: 'Sous-traitants' },
    ],
    backToChat: 'Retour au chat',
    controlsLink: 'Contrôles de confidentialité',
  },
  es: {
    title: 'Legal',
    subtitle: 'Términos, privacidad, cookies y subencargados de ExploreAI',
    links: [
      { id: 'terms', label: 'Términos del servicio' },
      { id: 'privacy', label: 'Política de privacidad' },
      { id: 'cookies', label: 'Política de cookies' },
      { id: 'subprocessors', label: 'Subencargados' },
    ],
    backToChat: 'Volver al chat',
    controlsLink: 'Controles de privacidad',
  },
};

/** Phase-0 legal body is English-only; hub labels stay localized. */
const DOCS_EN: Record<LegalDocId, LegalDocCopy> = {
  terms: {
    title: 'Terms of Service',
    subtitle: 'Phase-0 draft for ExploreAI cloud use',
    updated: 'Last updated: 2026-07-27',
    sections: [
      {
        heading: 'Service',
        body: 'ExploreAI provides AI chat, retrieval, and related tools on a best-effort basis. Features may change as the product evolves.',
      },
      {
        heading: 'Acceptable use',
        body: 'Do not abuse the service, attempt to bypass rate or plan quotas, submit unlawful content, or probe other users’ data. We may suspend access that harms the platform or other users.',
      },
      {
        heading: 'No warranty',
        body: 'Outputs are generated by third-party models and may be inaccurate. Do not rely on the service for legal, medical, or safety-critical decisions without independent review.',
      },
      {
        heading: 'Accounts and plans',
        body: 'Anonymous browser identity is available today. Paid plans, workspaces, and billing (when enabled) are governed by the plan limits published in product documentation.',
      },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    subtitle: 'How ExploreAI processes personal data',
    updated: 'Last updated: 2026-07-27',
    sections: [
      {
        heading: 'Controller',
        body: 'ExploreAI processes data to operate the product. Contact details for privacy requests will be published on the Privacy controls page as the service commercializes.',
      },
      {
        heading: 'Data we process',
        body: 'Client Identity cookies, chat messages you send, optional analytics preferences, and technical logs needed for security and reliability. Do not submit sensitive personal data you do not want processed by model providers.',
      },
      {
        heading: 'Retention and erasure',
        body: 'Inactive sessions and aged metrics are purged on a retention schedule (default about 90 days). You can erase this browser’s chat sessions from Privacy controls.',
      },
      {
        heading: 'Transfers',
        body: 'Model and infrastructure providers may process data in regions where they operate. See the Sub-processors page for the current list.',
      },
    ],
  },
  cookies: {
    title: 'Cookie Policy',
    subtitle: 'Cookies and similar technologies used by ExploreAI',
    updated: 'Last updated: 2026-07-27',
    sections: [
      {
        heading: 'Necessary',
        body: 'Client Identity (HttpOnly cookie) scopes chat sessions to your browser. It is required for session isolation and is not used for advertising.',
      },
      {
        heading: 'Optional analytics',
        body: 'If you accept analytics, we may load Datadog RUM and LaunchDarkly for product analytics and feature flags. You can change this preference anytime on Privacy controls.',
      },
      {
        heading: 'Storage',
        body: 'Consent preferences are stored in localStorage on your device. Clearing site data resets the consent banner.',
      },
    ],
  },
  subprocessors: {
    title: 'Sub-processors',
    subtitle: 'Third parties that may process data to deliver ExploreAI',
    updated: 'Last updated: 2026-07-27',
    sections: [
      {
        heading: 'LLM and search providers',
        body: 'Configured chat/completion and optional search providers process prompts and context to generate replies (for example OpenAI-compatible APIs used by the deployment).',
      },
      {
        heading: 'Hosting and delivery',
        body: 'Application hosting, CDN, and related infrastructure providers process connection metadata and application traffic for the deployed environment.',
      },
      {
        heading: 'Observability (optional)',
        body: 'If analytics consent is granted, Datadog may receive front-end RUM events. LaunchDarkly may receive flag evaluation events for feature management.',
      },
      {
        heading: 'Updates',
        body: 'This list is a Phase-0 draft and will be updated as commercial subprocessors are contracted. Material changes will be reflected on this page.',
      },
    ],
  },
};

export function legalHubCopy(lang: Language): LegalHubCopy {
  return HUB[lang] ?? HUB.en;
}

export function legalDocCopy(id: LegalDocId): LegalDocCopy {
  return DOCS_EN[id];
}
