server:
  port: 9000

spring:
  application:
    name: gateway

  webflux:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
